### ISSUE TITLE
关于同步与对齐的问题

### ISSUE THREAD

**Issue by coreeey** [zaocan666/SyncTalkNet#1]
您好，我觉得您写的这篇论文出发角度是非常有新意的，但是我有一个小小的疑问，您在AVA数据集创建了一个非对齐或者非同步子数据集，但是你在给TalkNet进行测试的时候，是否有按照你给标签的方式，重新训练呢？TalkNet中提出了一个TalkSet的数据集，他把同步与非对齐都认为是非同步的，同时测试的过程中，指标也是很高的（mAP>90%, 只针对同步和非对齐数据），所以说您是否有准备在TalkSet中进行测试啊：）

**Comment by zaocan666** [comment]
没有重新训练，创建的是测试数据集
在 TalkSet 上进行训练也许也能学到 synchronization cue，但与我们的方法还是有区别，之后确实可以拿来比较一下。

**Comment by coreeey** [comment]
好的，期待你开源的代码
