### ISSUE TITLE
聊天贴

### ISSUE THREAD

**Issue by ZY-WANG-0304** [zaocan666/SyncTalkNet#2]
你好，我在今天拜读了你们 RETHINKING AUDIO-VISUAL SYNCHRONIZATION FOR ACTIVE SPEAKER DETECTION 的工作。在说话人检测的任务中，考虑时间同步的问题非常符合实际产品的定义。请教一下，你们的模型有没有在中文的短视频数据上实验过？比如，抖音、快手的那种电影解说视频。

**Comment by zaocan666** [comment]
你好，你所说的电影解说视频确实属于以往ASD方法容易出错的情况，说话人声音与视频画面不符，但音视频中都有说话信号，以往ASD模型就会把视频中的人脸预测为 speaking，但这时视频声音属于解说者。在AVA数据集中有一些配音的视频，与电影解说视频的情况类似，我们在上面做了相关实验，但没有在中文短视频上进行实验，未来工作中可以考虑，谢谢你的关注。
